### PR TITLE
Major bug fix update

### PR DESCRIPTION
**Pull request by SuperTylerMan**
NavigationTeleOP.java
-Set the drive motors powers (Lines )
-Fixed all of the errors in the file that were found.

NavagationAuton.Java
-Fixed all of the errors in the file that were found -Added a few new void functions to the file

GamepadWrapper.java
-Added the GetButtonState function. Needs to be transfered over ASAP to the main branch.

CenterStageTeleOp.java
-Created documentation for the TeleOP OP modes.

Please check over the branch. This will need to be pushed back to main ASAP. Will create a pull request. Needs to be checked over right away.

Tyler M (SuperTylerMan) Stephen (jSdCool)

### CODE REVIEW

**Comment by Oscar3334** [comment]
For gamepad wrapper, you added back the things I intentionally deleted. If you do not like my previous changes, you should delete them and revert it closer to last year's, the code basically does the same thing twice. You also need to change RobotManager which currently works off the current version.

**Comment by jSdCool** [comment]
The Hash Maps should be removed as they will not work as intended. Due to the fact that the output of the maps is a boolean the values will never change, because booleans are primitives copying a boolean into a map does not automatically link the value of those references. Rather java creates a new boolean in memory that has that value, changing the value of the original boolean will not change the value of the new one. This property of primitives also holds true when using the wrapper classes.  Additionally the way this class is written it will produce a NullPointerException when you attempt to creat an instance of this class. This is because java will attempt to initialize the hash maps before it runs the constructor where gamepad1 and gamepad2 are assigned, thus they will both point to null before the code in the constructor is run. 

The gamepad wrapper class has 2 main proposes. The first is to abstract the interactions with the controllers so the rest of the code is simpler. the second is to provide an all in 1 place to manage the control layout. This way locations in the code only have to know about a specific action and not what it maps to on the controllers. 

Admittedly the analog values class does not do a good job at accomplishing this task however it is at leased better then directly accessing the values. Tt is also currently being used in elsewhere in the code so things would have to be re written if it was gotten rid of. Ideally a new solution should be implemented. I would caution removing the current implementation before a new solution is created and working.

It was also hard to determine what you were attempting to accomplish with modifications to the gamepad wrapper class (lack of documentation). Good documentation is essential when working on a big project sutch as this with many people. I know that in the past the team was realy bad at this but that does not mean that you can't start to fix that now.

This is just some advice, take it was you will.

**Comment by SuperTylerMan** [comment]
CLOSING BRANCH. This does not need to be merged back to main as another branch very similar was merged back to main

**Comment by SuperTylerMan** [comment]
Reopening the branch

**Review by pbnjam-es — APPROVED** [review]

**Pull request merged**
