### PR TITLE
Robot

### PR DESCRIPTION
**Pull request by Oscar3334**
Made a base of my idea for robot, do not pull robot_2.0, delete that branch actually.

Please leave your opinions, I tried to remove all the hashmaps, I want to know what y'all think about the nested classes, I really like them, but let me know if it causes any issues.

### CODE REVIEW

**Comment by Oscar3334** [comment]
Thanks for letting me know, the code is kinda a mess, will clean it up.

**Comment by SuperTylerMan** [comment]
Looks good!
Only suggestion I would add is to document the code so we can understand what type of parameter is being used. 
Did see you were removing the HashMaps for HardwareMaps instead.

Gonna have another person look at this before the pull request is approved.
Note: Oscar, I will need to work with you some point to work out the robot branch and position branch to get them fully finalized.

**Comment by jSdCool** [comment]
a few java things: 
1) if you want to access Config outside the robot class you need to do it via Robot.Config even if in the same class file
2) all variables in an Enum should be declared as final
3) in inheritance you can not override a static method (line 154)

other then that looks like it is coming along great keep up the good work.

**Comment by Oscar3334** [comment]
Fixed, and documented.
I skipped documenting the accessors, they seemed too trivial.

should switch actually be touchsensor? Using "switch" seems decieving. Is there a reason to use switch instead of touch sensor? should I rename it TouchSensorConfigs?

**Review by SuperTylerMan — APPROVED** [review]
Looks good. Fixed one of your documentation as you didn't add an extra *. 
Approving pull request. Wait until James and/or Arthur sees this before it is merged.

**Comment by jSdCool** [comment]
line 31 missing semi colon  

ServoConfigs really should have at leaded 1 state  

line 130 telemetry is spelled wrong  
line 138 slidesmotors is spelled wrong  

145-148 the encoders should never be reset during the run time of the robot especially for the slides as we kind of need to know where they are. Encoders should only be reset on initialization. as for why this is: [with reset](https://cdn.discordapp.com/attachments/787053362134777897/1058444267028217927/IMG_2806.mov?ex=6532c00a&is=65204b0a&hm=bb0894bf4204ab816ebb1ed5b8130425b88b96073c6cc5165d0c4764370fe5a2&)  ||  [without reset](https://cdn.discordapp.com/attachments/787053362134777897/1058443838416494693/IMG_2805.mov?ex=6532bfa4&is=65204aa4&hm=6c9efc7a6d268f1b6a6d14c23a34839a00b0746e22b4bc396c32dcae05ae1d6a&)

line 205 can not override a static method
line 206 you can not use super inside of a static method as the JVM has no idea if the method is being run inside of an instance of that object

line 214 should be DcMotor not DcMotors
line 219 should be SlidesMotors not DriveMotors

intellij should show errors for these if it does not then it is not set up correctly. let us know if you need help setting it up.

**Pull request merged**
